### ISSUE TITLE
Random but frequent crashes when entering a new zone

### ISSUE THREAD

**Issue by sirkibblesnbits** [Lost-Outpost/lost-legacy#88]
Odd issue when entering houses (in winterhold speciffically, although its happened when entering zones elsewhere.) It might just be a me issue but if it is, I don't know how to fix it. 
When I googled it, it says it may be a permission issue but I already made sure everything was allowed under every user, and I'm using the administer user anyway.

Here is the log it gives me when it crashes

> [2023-02-13 17:10:48.920 D] timing: MOApplication() 0 ms
[2023-02-13 17:10:48.921 D] timing: main() multiprocess 291 ms
[2023-02-13 17:10:48.921 D] command line: '"G:\lost legacy\ModOrganizer.exe" '
[2023-02-13 17:10:48.921 I] starting Mod Organizer version 2.4.4 revision 1df1ea5e in G:/lost legacy, usvfs: 0.5.6.0
[2023-02-13 17:10:48.921 I] data path: G:/lost legacy
[2023-02-13 17:10:48.921 I] working directory: G:/lost legacy
[2023-02-13 17:10:48.921 D] timing: MOApplication setup() 0 ms
[2023-02-13 17:10:49.673 E] [error.cpp:24] Unable to parse file "F:\SteamLibrary\steamapps\appmanifest_323850.acf": vdf.parse: unexpected EOF (open key quote?) (appmanifest_323850.acf, line 1)
[2023-02-13 17:10:49.674 E] [error.cpp:24] Unable to parse file "F:\SteamLibrary\steamapps\appmanifest_535520.acf": vdf.parse: unexpected EOF (open key quote?) (appmanifest_535520.acf, line 1)
[2023-02-13 17:10:49.674 E] [error.cpp:24] Unable to parse file "F:\SteamLibrary\steamapps\appmanifest_571310.acf": vdf.parse: unexpected EOF (open key quote?) (appmanifest_571310.acf, line 1)
[2023-02-13 17:10:50.595 I] using game plugin 'Skyrim Special Edition' ('SkyrimSE', variant (none), steam id '489830') at G:/lost legacy/Stock Game
[2023-02-13 17:15:06.677 I] [rootbuilder_plugin_mapper.py:37] Building...
[2023-02-13 17:15:06.678 I] [rootbuilder_plugin_mapper.py:40] Starting Root Exe = False
[2023-02-13 17:15:06.678 I] [rootbuilder.py:36] Running for version 1.5.97.0
[2023-02-13 17:15:06.678 I] [rootbuilder.py:39] RootBuilder: Starting build.
[2023-02-13 17:15:06.678 I] [rootbuilder.py:41] RootBuilder: Backing up files.
[2023-02-13 17:15:06.683 I] [rootbuilder.py:43] RootBuilder: Backed up files.
[2023-02-13 17:15:06.683 I] [rootbuilder.py:50] RootBuilder: Copying files.
[2023-02-13 17:15:07.090 I] [rootbuilder.py:52] RootBuilder: Files copied.
[2023-02-13 17:15:07.090 I] [rootbuilder.py:54] RootBuilder: Build complete.
[2023-02-13 17:15:07.090 I] [rootbuilder_plugin_mapper.py:59] Redirecting
[2023-02-13 18:07:59.573 I] [rootbuilder.py:66] Running for version 1.5.97.0
[2023-02-13 18:07:59.606 I] [rootbuilder.py:69] RootBuilder: Starting clear.
[2023-02-13 18:07:59.607 I] [rootbuilder.py:71] RootBuilder: Clearing any links.
[2023-02-13 18:07:59.613 I] [rootbuilder.py:73] RootBuilder: Links cleared.
[2023-02-13 18:07:59.613 I] [rootbuilder.py:75] RootBuilder: Clearing any copied files.
[2023-02-13 18:08:01.167 E] [error.cpp:24] Traceback (most recent call last):
[2023-02-13 18:08:01.168 E] [error.cpp:24]   File "G:/lost legacy/plugins\rootbuilder\rootbuilder\plugins\rootbuilder_plugin_mapper.py", line 20, in <lambda>
[2023-02-13 18:08:01.176 E] [error.cpp:24]     self.organiser.onFinishedRun(lambda appName, resultCode: self.clear(appName, resultCode))
[2023-02-13 18:08:01.176 E] [error.cpp:24]   File "G:/lost legacy/plugins\rootbuilder\rootbuilder\plugins\rootbuilder_plugin_mapper.py", line 52, in clear
[2023-02-13 18:08:01.176 E] [error.cpp:24]     self.rootBuilder.clear()
[2023-02-13 18:08:01.176 E] [error.cpp:24]   File "G:/lost legacy/plugins\rootbuilder\rootbuilder\rootbuilder.py", line 76, in clear
[2023-02-13 18:08:01.180 E] [error.cpp:24]     self.copier.clear()
[2023-02-13 18:08:01.180 E] [error.cpp:24]   File "G:/lost legacy/plugins\rootbuilder\rootbuilder\modules\rootbuilder_copy.py", line 105, in clear
[2023-02-13 18:08:01.186 E] [error.cpp:24]     self.sync()
[2023-02-13 18:08:01.186 E] [error.cpp:24]   File "G:/lost legacy/plugins\rootbuilder\rootbuilder\modules\rootbuilder_copy.py", line 80, in sync
[2023-02-13 18:08:01.186 E] [error.cpp:24]     fileHash = str(self.utilities.hashFile(file))
[2023-02-13 18:08:01.186 E] [error.cpp:24]   File "G:/lost legacy/plugins\rootbuilder\shared\shared_utilities.py", line 53, in hashFile
[2023-02-13 18:08:01.190 E] [error.cpp:24]     f = os.open(path, (os.O_RDWR | os.O_BINARY))
[2023-02-13 18:08:01.191 E] [error.cpp:24] PermissionError: [Errno 13] Permission denied: 'G:\\lost legacy\\Stock Game\\SkyrimSE.exe'
[2023-02-13 18:08:01.196 E] uncaught exception in handler (object , eventtype 3): Traceback (most recent call last):
[2023-02-13 18:08:01.196 E]   File "G:/lost legacy/plugins\rootbuilder\rootbuilder\plugins\rootbuilder_plugin_mapper.py", line 20, in <lambda>
[2023-02-13 18:08:01.196 E]     self.organiser.onFinishedRun(lambda appName, resultCode: self.clear(appName, resultCode))
[2023-02-13 18:08:01.196 E]   File "G:/lost legacy/plugins\rootbuilder\rootbuilder\plugins\rootbuilder_plugin_mapper.py", line 52, in clear
[2023-02-13 18:08:01.196 E]     self.rootBuilder.clear()
[2023-02-13 18:08:01.196 E]   File "G:/lost legacy/plugins\rootbuilder\rootbuilder\rootbuilder.py", line 76, in clear
[2023-02-13 18:08:01.196 E]     self.copier.clear()
[2023-02-13 18:08:01.196 E]   File "G:/lost legacy/plugins\rootbuilder\rootbuilder\modules\rootbuilder_copy.py", line 105, in clear
[2023-02-13 18:08:01.196 E]     self.sync()
[2023-02-13 18:08:01.196 E]   File "G:/lost legacy/plugins\rootbuilder\rootbuilder\modules\rootbuilder_copy.py", line 80, in sync
[2023-02-13 18:08:01.196 E]     fileHash = str(self.utilities.hashFile(file))
[2023-02-13 18:08:01.196 E]   File "G:/lost legacy/plugins\rootbuilder\shared\shared_utilities.py", line 53, in hashFile
[2023-02-13 18:08:01.196 E]     f = os.open(path, (os.O_RDWR | os.O_BINARY))
[2023-02-13 18:08:01.196 E] PermissionError: [Errno 13] Permission denied: 'G:\\lost legacy\\Stock Game\\SkyrimSE.exe'
[2023-02-13 18:08:01.196 E] 
[2023-02-13 18:08:01.197 E] an error occurred: Traceback (most recent call last):
[2023-02-13 18:08:01.197 E]   File "G:/lost legacy/plugins\rootbuilder\rootbuilder\plugins\rootbuilder_plugin_mapper.py", line 20, in <lambda>
[2023-02-13 18:08:01.197 E]     self.organiser.onFinishedRun(lambda appName, resultCode: self.clear(appName, resultCode))
[2023-02-13 18:08:01.197 E]   File "G:/lost legacy/plugins\rootbuilder\rootbuilder\plugins\rootbuilder_plugin_mapper.py", line 52, in clear
[2023-02-13 18:08:01.197 E]     self.rootBuilder.clear()
[2023-02-13 18:08:01.197 E]   File "G:/lost legacy/plugins\rootbuilder\rootbuilder\rootbuilder.py", line 76, in clear
[2023-02-13 18:08:01.197 E]     self.copier.clear()
[2023-02-13 18:08:01.197 E]   File "G:/lost legacy/plugins\rootbuilder\rootbuilder\modules\rootbuilder_copy.py", line 105, in clear
[2023-02-13 18:08:01.197 E]     self.sync()
[2023-02-13 18:08:01.197 E]   File "G:/lost legacy/plugins\rootbuilder\rootbuilder\modules\rootbuilder_copy.py", line 80, in sync
[2023-02-13 18:08:01.197 E]     fileHash = str(self.utilities.hashFile(file))
[2023-02-13 18:08:01.197 E]   File "G:/lost legacy/plugins\rootbuilder\shared\shared_utilities.py", line 53, in hashFile
[2023-02-13 18:08:01.197 E]     f = os.open(path, (os.O_RDWR | os.O_BINARY))
[2023-02-13 18:08:01.197 E] PermissionError: [Errno 13] Permission denied: 'G:\\lost legacy\\Stock Game\\SkyrimSE.exe'
[2023-02-13 18:08:01.197 E]

**Comment by sirkibblesnbits** [comment]
[Crash_2023_2_13_16-33-12.txt](https://github.com/Lost-Outpost/lost-legacy/files/10727231/Crash_2023_2_13_16-33-12.txt)
also heres the crashlog

**Comment by GreatPadinski** [comment]
Up your pagefile: 
Pagefile and Memory Crashes
Bigger Skyrim modlists need a lot of memory, and when there is not enough available it may fail allocating more. To fix this, you'll want to have a bigger pagefile.

A pagefile is a file on your disk Windows will use when there is not enough RAM available.

Never disable the pagefile - this may lead to various issues on your system, such as this Skyrim crash.

If you've never touched the pagefile, try performing the following steps:
1. Press Windows + R on your keyboard and enter sysdm.cpl ,3
2. Under the Performance section, press 'Settings'
3. Go to the Advanced tab at the top, and at the Virtual memory section press 'Change...'
4. Disable 'Automatically manage paging file size for all drives'
5. If you have more than one drive, try enabling it for at least one more drive as a backup (make sure it has a decent bit of free space, like 15GB). Set the size to 'System managed size'.
Otherwise, set a custom size for the drive it's currently on and increase the maximum size to be at least 20GB.
